### ISSUE TITLE
Não consigo integrar com SandBox

### ISSUE THREAD

**Issue by CEduardo899** [pagseguro/android#16]
Boa tarde,
verificando o código da PagSeguro.class verifiquei que o mesmo endereço de produção esta para o SandBox.
PRODUCTION("https://ws.wallet.pagseguro.uol.com.br/mobile-gateway", "https://df.uol.com.br"),
SANDBOX("https://ws.wallet.pagseguro.uol.com.br/mobile-gateway", "https://df.uol.com.br"),

Outra coisa, quando utilizo a versão 0.4 com o Token de produção eu consigo realizar o pagamento, porem fica instável as vezes da certo outras não e os pagamentos que dão certo vão para o ambiente de produção, conforme print abaixo.

![psproducao](https://cloud.githubusercontent.com/assets/13140027/8462600/6303caf8-200b-11e5-993b-accfebbd7552.jpg)

Quando mudo o Token para SandBox sempre da erro. Quando utilizo a versão 0.7 sempre da erro tanto com o Token de produção e SandBox.
Segue abaixo o trecho do código que estou utilizando.O Token que esta codigo é do SandBox

BigDecimal amount = new BigDecimal("10.0");
        //quantidade de parcelas
        int quantityParcel = 1;
        PagSeguro.pay(new PagSeguroRequest()
                        .withNewItem("Item Description", quantityParcel, amount)
                        .withVendorEmail("carloseduardo_15@hotmail.com")
                        .withBuyerEmail("comprador@mail.com.br")
                        .withBuyerCPF("00000000000")
                        .withBuyerCellphoneNumber("5511000000000")
                        .withReferenceCode("123")
                        .withEnvironment(PagSeguro.Environment.SANDBOX)            .   withAuthorization("carloseduardo_15@hotmail.com","0F927F7621894E049235971F0BF2F399"),

                getActivity(),
                R.id.frame_container,
                new PagSeguro.PagSeguroListener() {
                    @Override
                    public void onSuccess(PagSeguroResponse response, Context context) {
                        Toast.makeText(context, "Lib PS retornou pagamento aprovado! " + response, Toast.LENGTH_LONG).show();
                    }

                    @Override
                    public void onFailure(PagSeguroResponse response, Context context) {
                        Log.e("Dudu", response.getMessage());
                        Toast.makeText(context, "Lib PS retornou FALHA no pagamento! " + response, Toast.LENGTH_LONG).show();

                    }
                });

**Comment by ranieripieper** [comment]
Estou tendo o mesmo problema. 
Você conseguiu resolver de alguma forma?

**Comment by CEduardo899** [comment]
Não, utilizei outra API.

**Comment by ranieripieper** [comment]
Qual API vc utilizou Eduardo?

**Comment by CEduardo899** [comment]
PayPal. Mais tem duas coisas que não gostei. A primeira que ele te redireciona para o PayPal e a opção de pagar direto com o cartão de credito não esta liberada para o pt-BR, ou seja o usuário tem que ter uma conta no PayPal. Não sei quando eles vão disponibilizar o pagamento direto pelo cartão de credito para o pt-BR. Mais a implementação é tranquila

**Comment by ranieripieper** [comment]
Obrigado Eduardo

**Comment by jerodac** [comment]
SandBox está fora no momento... integração com a lib somente em produção.
Obrigado, qualquer duvida pergunte.

**Comment by fkamlesh** [comment]
Olá Jean Rodrigo,

Por favor, forneça o lib do Ambiente Sandbox para testar propósito.
Eu quero testar o meu primeiro Android App para caixa de areia.

Saudações
Kamlesh
