### ISSUE TITLE
Pagamento via boleto

### ISSUE THREAD

**Issue by heloisasim** [pagseguro/android#18]
A funcionalidade de gerar boletos vai ser adicionada na biblioteca? Existe alguma previsão?

**Comment by jerodac** [comment]
Bom dia Heloisa.

Está funcionalidade no momento não está disponivel na lib, não é possivel estipular uma previsão para essa funcionalidade.
Para utilizar mais recursos você pode estar usando o modo App2App com nosso App da Carteira PagSeguro.
Para mais informações confira nossa documentação que se encontra aqui no github.

Qualquer duvida estamos à Disposição.

Att,
Jean Rodrigo D. Cunha
Developer at PagSeguro
